// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

/************************************************************/
/**
 * 
 */
public class Agent_turism {
	/**
	 * 
	 */
	private int vechime;
	/**
	 * 
	 */
	private String angajatID;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param dep 
	 */
	public void schimbareDepartament(Departament dep) {
	}

	/**
	 * 
	 * @param valoare 
	 */
	public void acordareDiscount(int valoare) {
	}

	/**
	 * 
	 */
	public void timpPensionare() {
	}
}
