// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private float buget;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param buget 
	 */
	public void stabilireBuget(float buget) {
	}

	/**
	 * 
	 */
	public void adaugareRezervare() {
	}

	/**
	 * 
	 * @param rezervare 
	 */
	public void anulareRezervare(Rezervare rezervare) {
	}

	/**
	 * 
	 */
	public void feedback() {
	}
}
