// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Departament {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String buget;//int?
	/**
	 * 
	 */
	private Locatii locatieDepartament;
	//un vector de persoane in care se regasesc angajatii?
	private List<Persoana> angajati;//nu era
	/**
	 * 
	 */
	private int nrAngajati;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	public void angajare(Agent_turism agent) {//nu avea referinta catre agent
	}

	/**
	 * 
	 * @param agent 
	 */
	public void concediere(Agent_turism agent) {
	}

	/**
	 * 
	 * @param agent 
	 */
	public void atribuireProiect(Agent_turism agent) {
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getBuget() {
		return buget;
	}

	public void setBuget(String buget) {
		this.buget = buget;
	}

	public Locatii getLocatieDepartament() {
		return locatieDepartament;
	}

	public void setLocatieDepartament(Locatii locatieDepartament) {
		this.locatieDepartament = locatieDepartament;
	}

	public int getNrAngajati() {
		return nrAngajati;
	}

	public void setNrAngajati(int nrAngajati) {
		this.nrAngajati = nrAngajati;
	}
	
	
	
}
