// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

/************************************************************/
/**
 * 
 */
public class Departament {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String buget;
	/**
	 * 
	 */
	private Locatii locatieDepartament;
	/**
	 * 
	 */
	private int nrAngajati;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 */
	public void angajare() {
	}

	/**
	 * 
	 * @param agent 
	 */
	public void concediere(Agent_turism agent) {
	}

	/**
	 * 
	 * @param agent 
	 */
	public void atribuireProiect(Agent_turism agent) {
	}
}
