// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Firma {
	/**
	 * 
	 */
	private String Nume;
	/**
	 * 
	 */
	private String locatieSediu;
	/**
	 * 
	 */
	private float capital;
	/**
	 * 
	 */
	private int nrDepartamente;
	//lista cu toate departamentele? si aici sa fie adaugat departamentul
	private List<Departament> departamente;
	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param dep 
	 */
	public void alocareBuget(Departament dep, String buget) {
		dep.setBuget(buget);
	}

	/**
	 * 
	 */
	public void adaugareDepartament() {
	}

	/**
	 * 
	 * @param dep 
	 */
	public void stergereDepartament(Departament dep) {
		if(departamente != null) {
			departamente.remove(departamente.stream().filter(e -> e.equals(dep)).findFirst().get());
		}
	}
}
