// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

/************************************************************/
/**
 * 
 */
public class Firma {
	/**
	 * 
	 */
	private String Nume;
	/**
	 * 
	 */
	private String locatieSediu;
	/**
	 * 
	 */
	private float capital;
	/**
	 * 
	 */
	private int nrDepartamente;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param dep 
	 */
	public void alocareBuget(Departament dep) {
	}

	/**
	 * 
	 */
	public void adaugareDepartament() {
	}

	/**
	 * 
	 * @param dep 
	 */
	public void stergereDepartament(Departament dep) {
	}
}
