// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

/************************************************************/
/**
 * 
 */
public class Persoana extends Client {
	/**
	 * 
	 */
	protected String nume;
	/**
	 * 
	 */
	protected String prenume;
	/**
	 * 
	 */
	protected String CNP;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param loc 
	 */
	public void propunereLocatie(Locatii loc) {
	}

	/**
	 * 
	 * @param nume 
	 * @param prenume 
	 * @param CNP 
	 */
	public void modificareDatePersonale(String nume, String prenume, String CNP) {
	}

	/**
	 * 
	 */
	public void deschidereCont() {
	}
}
