// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Proiect_v2;

/************************************************************/
/**
 * 
 */
public class Rezervare {
	/**
	 * 
	 */
	private String codIdentificare;
	/**
	 * 
	 */
	private String dataRezervare;
	/**
	 * 
	 */
	private float cost;
	/**
	 * 
	 */
	public Client client;

	/**
	 * 
	 */
	public void afisare() {
	}

	/**
	 * 
	 * @param data 
	 */
	public void schimbareData(String data) {
	}

	/**
	 * 
	 */
	public void asigurareTransport() {
	}
}
